services:
  s1app:
    image: postgres:latest
    container_name: 68-s1-app
    ports:
      - ${APP_PORT}:1137
    environment:
      POSTGRES_USER: ${DATSBETE_USER}
      POSTGRES_PASSWORD: ${DATSBETE_PASS}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      POSTGRES_DB: ${DATSBETE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATSBETE_PORT}